namespace: kube-system

commonLabels:
  app: floating-ip-controller

resources:
- serviceaccount.yaml
- rbac.yaml
- deployment.yaml

images:
- name: floating-ip-controller
  newName: mwthink/digitalocean-floating-ip-controller
  newTag: v0.2.0
