---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floating-ip-controller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: floating-ip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: floating-ip-controller
subjects:
- kind: ServiceAccount
  name: floating-ip-controller
